import { Metadata } from "next";
import "./global.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const AppLayout = ({
  children,
}: Readonly<{
  children: React.ReactElement;
}>) => {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};

export default AppLayout;
