import { Metadata } from "next";
import localFont from "next/font/local";
import "./global.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = localFont({
  src: [
    { path: "../public/fonts/Roboto-Bold.ttf" },
    { path: "../public/fonts/Roboto-Regular.ttf" },
    { path: "../public/fonts/Roboto-Thin.ttf" },
  ],
  variable: "--font-roboto",
});

const AppLayout = ({
  children,
}: Readonly<{
  children: React.ReactElement;
}>) => {
  return (
    <html lang="en" className={roboto.variable}>
      <body>{children}</body>
    </html>
  );
};

export default AppLayout;
