export { default as Navbar } from "./Navbar/Navbar";
export { default as Footer } from "./Footer/Footer";
export { default as Hero } from "./Hero/Hero";
export { default as Parallax } from "./Parallax/Parallax";
export { default as Achievements } from "./Achievements/Achievements";
export { default as Transformations } from "./Transformations/Transformations";
export { default as Testimonials } from "./Testimonials/Testimonials";
export { default as GetStarted } from "./GetStarted/GetStarted";
export { default as Services } from "./Services/Services";
