export default [
  "No Excuses",
  "Stay Strong",
  "Push Harder",
  "Be Unstoppable",
  "Lift Heavy",
  "Grind Daily",
  "Stay Hungry",
  "Break Limits",
  "Feel Alive",
  "Own It",
  "Train Hard",
  "Never Quit",
  "Stay Disciplined",
  "Be Consistent",
  "Crush Goals",
  "Rise Up",
  "Mind Over Muscle",
  "Progress, Not Perfection",
  "Sweat, Smile, Repeat",
  "Conquer Yourself",
];
