name: Django_CRM TEST CI
run-name: "${{ github.actor }} on ${{ github.ref_name }}: ${{ github.event.head_commit.message }} (${{ github.event_name }})"

on:
  push:
    branches:
      - django_crm
  pull_request:
    branches:
      - django_crm

permissions:
  contents: read

jobs:
  Build_and_Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-versions: [3.9, 3.11, 3.13]
        os: [windows-latest]
      max-parallel: 3
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-versions }}
          cache: pip

      - name: Setup Virtual Environment
        run: |
          python -m venv venv

      - name: Activate Virtual Environment on Linux/macOS
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: source venv/bin/activate

      - name: Activate Virtual Environment on Windows
        if: runner.os == 'Windows'
        run: ./venv/Scripts/activate.bat

      - name: Install Dependencies
        run: |
          pip install --upgrade pip 
          pip install -r requirements.txt

      - name: Run Tests
        run: python manage.py test
