name: Django_CRM TEST CI
run-name: CI triggered by ${{ github.actor }} on ${{ github.ref }}

on:
  push:
    branches:
      - django_crm
  pull_request:
    branches:
      - django_crm

jobs:
  Build_and_Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-versions: [3.9, 3.11, 3.13]
        os: [ubuntu-latest, windows-latest]
      max-parallel: 3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-versions }}
          cache: pip
      - name: Setup and Activate Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate
      - name: Install Dependencies
        run: |
          pip install --upgrade pip 
          pip install -r requirements.txt
      - name: Run Tests
        run: python manage.py test
